"""
M10 — Louvain Community Detection for Aid Allocation Clustering
Groups IGAD regions into 4-8 clusters based on:
  - Hazard similarity (cosine similarity of signal vectors)
  - Geographic adjacency (shared border)
  - Causal graph connectivity (VARLiNGAM edge density)

Cluster labels generated by Groq LLM.
Maps to GraphAlpha: community detection for portfolio clustering.
"""

import networkx as nx
import numpy as np
from dataclasses import dataclass
from datetime import datetime

try:
    import community as community_louvain  # python-louvain
except ImportError:
    community_louvain = None


@dataclass
class HazardCluster:
    cluster_id: int
    label: str
    member_regions: list[str]
    dominant_hazard: str
    cluster_risk_score: float
    centroid_lat: float
    centroid_lon: float


REGION_COORDS = {
    'ethiopia': (9.1, 40.5),
    'kenya': (-0.0, 37.9),
    'somalia': (5.2, 45.3),
    'sudan': (12.9, 30.2),
    'south_sudan': (7.0, 30.0),
    'uganda': (1.4, 32.3),
    'djibouti': (11.8, 42.6),
    'eritrea': (15.2, 39.5),
    'tanzania': (-6.4, 34.9),
    'burundi': (-3.4, 29.9),
    'rwanda': (-2.0, 29.9),
}


class LouvainHazardClustering:
    REGIME_ENCODING = {
        'Baseline': 0, 'DroughtOnset': 1,
        'SevereDrought': 2, 'FloodWatch': 3, 'FloodEmergency': 4
    }

    def build_similarity_graph(
        self,
        risk_scores: dict[str, float],
        regimes: dict[str, str],
        spi_values: dict[str, float],
        causal_edge_density: dict[tuple, float]
    ) -> nx.Graph:
        """
        Build undirected similarity graph.
        Edge weight = hazard_similarity × geographic_proximity
        """
        G = nx.Graph()
        regions = list(REGION_COORDS.keys())
        for r in regions:
            G.add_node(r,
                       risk_score=risk_scores.get(r, 50.0),
                       regime=regimes.get(r, 'Baseline'),
                       spi=spi_values.get(r, 0.0))

        for i, r1 in enumerate(regions):
            for r2 in regions[i + 1:]:
                # Hazard similarity (cosine of feature vectors)
                v1 = np.array([
                    risk_scores.get(r1, 50) / 100,
                    spi_values.get(r1, 0) / 3,
                    self.REGIME_ENCODING.get(regimes.get(r1, 'Baseline'), 0) / 4
                ])
                v2 = np.array([
                    risk_scores.get(r2, 50) / 100,
                    spi_values.get(r2, 0) / 3,
                    self.REGIME_ENCODING.get(regimes.get(r2, 'Baseline'), 0) / 4
                ])
                cos_sim = float(
                    np.dot(v1, v2) / (np.linalg.norm(v1) * np.linalg.norm(v2) + 1e-8)
                )

                # Geographic proximity
                lat1, lon1 = REGION_COORDS[r1]
                lat2, lon2 = REGION_COORDS[r2]
                dist = np.sqrt((lat1 - lat2) ** 2 + (lon1 - lon2) ** 2)
                geo_sim = 1.0 / (1.0 + dist / 10.0)

                # Causal edge density
                causal_w = causal_edge_density.get((r1, r2), 0.0) + \
                           causal_edge_density.get((r2, r1), 0.0)

                edge_weight = (0.5 * cos_sim + 0.3 * geo_sim +
                               0.2 * causal_w)
                if edge_weight > 0.1:
                    G.add_edge(r1, r2, weight=edge_weight)

        return G

    def detect_clusters(
        self, G: nx.Graph
    ) -> dict[str, int]:
        """
        Apply Louvain algorithm.
        Returns {region_id: cluster_id} partition.
        """
        if community_louvain is None:
            return self._geographic_fallback(G)

        partition = community_louvain.best_partition(
            G, weight='weight', random_state=42
        )
        return partition

    def _geographic_fallback(
        self, G: nx.Graph
    ) -> dict[str, int]:
        """Fallback: 4 geographic clusters."""
        clusters = {
            'ethiopia': 0, 'eritrea': 0, 'djibouti': 0,
            'somalia': 1,
            'kenya': 2, 'uganda': 2, 'tanzania': 2,
            'rwanda': 2, 'burundi': 2,
            'sudan': 3, 'south_sudan': 3
        }
        return clusters

    async def generate_cluster_label(
        self,
        cluster_id: int,
        member_regions: list[str],
        dominant_hazard: str,
        groq_client
    ) -> str:
        """LLM generates human-readable cluster name."""
        try:
            region_list = ', '.join(
                r.replace('_', ' ').title() for r in member_regions
            )
            resp = await groq_client.chat.completions.create(
                model='llama-3.3-70b-versatile',
                messages=[{
                    'role': 'user',
                    'content': (
                        f'Generate a short geographic name (max 6 words) for '
                        f'this cluster of East African regions: {region_list}. '
                        f'Current dominant hazard: {dominant_hazard}. '
                        f'Examples: "Horn of Africa Drought Corridor", '
                        f'"Great Lakes Food Security Zone". '
                        f'Output the name only.'
                    )
                }],
                temperature=0.3,
                max_tokens=20
            )
            return resp.choices[0].message.content.strip()
        except Exception:
            return f'Cluster {cluster_id}: {dominant_hazard} Zone'

    async def run(
        self,
        risk_scores: dict[str, float],
        regimes: dict[str, str],
        spi_values: dict[str, float],
        causal_density: dict[tuple, float],
        neo4j_session,
        groq_client
    ) -> list[HazardCluster]:
        """Full clustering pipeline with Neo4j write-back."""
        G = self.build_similarity_graph(
            risk_scores, regimes, spi_values, causal_density
        )
        partition = self.detect_clusters(G)

        # Group regions by cluster
        cluster_members: dict[int, list[str]] = {}
        for region, cid in partition.items():
            cluster_members.setdefault(cid, []).append(region)

        clusters = []
        for cid, members in cluster_members.items():
            dominant = max(
                set(regimes.get(m, 'Baseline') for m in members),
                key=lambda x: list(regimes.values()).count(x)
            )
            c_risk = max(risk_scores.get(m, 0) for m in members)
            lats = [REGION_COORDS[m][0] for m in members]
            lons = [REGION_COORDS[m][1] for m in members]

            label = await self.generate_cluster_label(
                cid, members, dominant, groq_client
            )
            cluster = HazardCluster(
                cluster_id=cid,
                label=label,
                member_regions=members,
                dominant_hazard=dominant,
                cluster_risk_score=c_risk,
                centroid_lat=float(np.mean(lats)),
                centroid_lon=float(np.mean(lons))
            )
            clusters.append(cluster)

            # Write to Neo4j
            await neo4j_session.run(
                'MERGE (c:HazardCluster {id: $cid}) '
                'SET c.label = $label, c.dominant_hazard = $dom, '
                '    c.cluster_risk_score = $risk, '
                '    c.centroid_lat = $lat, c.centroid_lon = $lon, '
                '    c.member_count = $n, c.updated_at = $now',
                cid=f'cluster_{cid}',
                label=label, dom=dominant, risk=c_risk,
                lat=cluster.centroid_lat, lon=cluster.centroid_lon,
                n=len(members),
                now=datetime.utcnow().isoformat()
            )
            for member in members:
                await neo4j_session.run(
                    'MATCH (r:Region {id: $rid}) '
                    'MATCH (c:HazardCluster {id: $cid}) '
                    'MERGE (r)-[:BELONGS_TO_CLUSTER]->(c)',
                    rid=member, cid=f'cluster_{cid}'
                )

        return clusters